apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capm3.fullname" . }}-capm3-capm3fasttrack-configmap
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  {{- include "capm3.labels" . | nindent 4 }}
data:
  CAPM3_FAST_TRACK: {{ .Values.capm3Capm3FasttrackConfigmap.capm3FastTrack | quote
    }}