apiVersion: v1
kind: Service
metadata:
  name: {{ include "capm3.fullname" . }}-ipam-webhook-service
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  {{- include "capm3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ipamWebhookService.type }}
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
  {{- include "capm3.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ipamWebhookService.ports | toYaml | nindent 2 -}}